- hosts: all
  any_errors_fatal: true
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

#    - name: Include the hardening role
#      ansible.builtin.include_role:
#        name: konstruktoid.hardening
#      vars:
#        block_blacklisted: true
#        sshd_admin_net:
#          - 192.168.2.0/24
#          - 192.168.105.0/24
#        suid_sgid_permissions: false
